### PR TITLE
Navigate mode

### PR DESCRIPTION
**Pull request by nwaughachukwuma**
Hey @brh55, I am done with the PR proposal for issue #26 and #27. Please let me know what you think about it.

### CODE REVIEW

**Comment by brh55** [comment]
@nwaughachukwuma This looks great! 

One thing, I'm thinking it would be better to just ignore the start option if "navigate" is present, and to warn the user.

Therefore, if the users intent is to turn on "navigation", but wasn't aware of the "start / navigate" combination working, we can still be forgiving and just let the platform handle it.

> "If the user specifies an origin and it is not close to the user's current location, or the user's current location is unavailable, the map launches a route preview. If the user does not specify an origin (in which case the origin defaults to the user's current location), or the origin is close to the user's current location, the map launches turn-by-turn navigation." - Google Maps URL

**Comment by nwaughachukwuma** [comment]
Alright @brh55 I will make modifications as such. Thanks

**Comment by nwaughachukwuma** [comment]
@brh55 I just made the changes as you suggested. Please take a look

**Comment by brh55** [comment]
Approved! And will bump the version and merge 👍, thanks so much @nwaughachukwuma

**Pull request merged**
