### PR TITLE
Fix for https://github.com/brh55/react-native-open-maps/issues/5#issu…

### PR DESCRIPTION
**Pull request by tspiva**
Fix for https://github.com/brh55/react-native-open-maps/issues/5#issuecomment-399297212

### CODE REVIEW

**Comment by tspiva** [comment]
Fix for https://github.com/brh55/react-native-open-maps/issues/5#issuecomment-399297212

**Comment by brh55** [comment]
@tspiva Looks good, but could you also add in the update for the text.
image

**Comment by tspiva** [comment]
@brh55 I committed the fix. Sorry about that.

**Comment by brh55** [comment]
@tspiva thanks again! merged, and will publish in a second

**Pull request merged**
